# Generated by Django 5.2.3 on 2025-07-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="content",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to=""),
        ),
    ]
